# Generated by Django 4.2.16 on 2024-10-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shibuyamenapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ramenshop",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ramenshop",
            name="opening_hours",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
