# Generated by Django 4.2.16 on 2024-10-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shibuyamenapp", "0003_ramenshop_location_ramenshop_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ramenshop",
            name="location_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ramenshop",
            name="location_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
